<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Mon Dec 17 19:19:07 UTC 2018.

define('DOMJUDGE_VERSION', '6.0.3');

define('BINDIR',      '/opt/domjudge/domserver/bin');
define('ETCDIR',      '/opt/domjudge/domserver/etc');
define('WWWDIR',      '/opt/domjudge/domserver/www');
define('WEBAPPDIR',   '/opt/domjudge/domserver/webapp');
define('LIBDIR',      '/opt/domjudge/domserver/lib');
define('SQLDIR',      '/opt/domjudge/domserver/sql');
define('LIBVENDORDIR','/opt/domjudge/domserver/lib/vendor');
define('LIBWWWDIR',   '/opt/domjudge/domserver/lib/www');
define('LIBSUBMITDIR','/opt/domjudge/domserver/lib/submit');
define('LOGDIR',      '/opt/domjudge/domserver/log');
define('RUNDIR',      '/opt/domjudge/domserver/run');
define('TMPDIR',      '/opt/domjudge/domserver/tmp');
define('SUBMITDIR',   '/opt/domjudge/domserver/submissions');

define('BASEURL',     'http://localhost/');

define('SUBMITCLIENT_ENABLED', 'yes');
