<?php

namespace Proxies\__CG__\DOMJudgeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Submission extends \DOMJudgeBundle\Entity\Submission implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'submitid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'origsubmitid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'cid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'teamid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'probid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'langid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'submittime', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'judgehost', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'valid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'rejudgingid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'expected_results', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'entry_point', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'contest', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'language', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'team', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'problem', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'judgings', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'files', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'balloons'];
        }

        return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'submitid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'origsubmitid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'cid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'teamid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'probid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'langid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'submittime', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'judgehost', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'valid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'rejudgingid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'expected_results', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'entry_point', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'contest', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'language', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'team', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'problem', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'judgings', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'files', '' . "\0" . 'DOMJudgeBundle\\Entity\\Submission' . "\0" . 'balloons'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Submission $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSubmitid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSubmitid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmitid', []);

        return parent::getSubmitid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigsubmitid($origsubmitid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigsubmitid', [$origsubmitid]);

        return parent::setOrigsubmitid($origsubmitid);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigsubmitid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigsubmitid', []);

        return parent::getOrigsubmitid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCid($cid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCid', [$cid]);

        return parent::setCid($cid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCid', []);

        return parent::getCid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeamid($teamid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeamid', [$teamid]);

        return parent::setTeamid($teamid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeamid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeamid', []);

        return parent::getTeamid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProbid($probid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProbid', [$probid]);

        return parent::setProbid($probid);
    }

    /**
     * {@inheritDoc}
     */
    public function getProbid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProbid', []);

        return parent::getProbid();
    }

    /**
     * {@inheritDoc}
     */
    public function setLangid($langid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLangid', [$langid]);

        return parent::setLangid($langid);
    }

    /**
     * {@inheritDoc}
     */
    public function getLangid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLangid', []);

        return parent::getLangid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmittime($submittime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmittime', [$submittime]);

        return parent::setSubmittime($submittime);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmittime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmittime', []);

        return parent::getSubmittime();
    }

    /**
     * {@inheritDoc}
     */
    public function setJudgehost($judgehost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJudgehost', [$judgehost]);

        return parent::setJudgehost($judgehost);
    }

    /**
     * {@inheritDoc}
     */
    public function getJudgehost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJudgehost', []);

        return parent::getJudgehost();
    }

    /**
     * {@inheritDoc}
     */
    public function setValid($valid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValid', [$valid]);

        return parent::setValid($valid);
    }

    /**
     * {@inheritDoc}
     */
    public function getValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValid', []);

        return parent::getValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setRejudgingid($rejudgingid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRejudgingid', [$rejudgingid]);

        return parent::setRejudgingid($rejudgingid);
    }

    /**
     * {@inheritDoc}
     */
    public function getRejudgingid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRejudgingid', []);

        return parent::getRejudgingid();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpectedResults($expectedResults)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpectedResults', [$expectedResults]);

        return parent::setExpectedResults($expectedResults);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpectedResults()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpectedResults', []);

        return parent::getExpectedResults();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntryPoint($entryPoint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntryPoint', [$entryPoint]);

        return parent::setEntryPoint($entryPoint);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryPoint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryPoint', []);

        return parent::getEntryPoint();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeam(\DOMJudgeBundle\Entity\Team $team = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeam', [$team]);

        return parent::setTeam($team);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeam', []);

        return parent::getTeam();
    }

    /**
     * {@inheritDoc}
     */
    public function addJudging(\DOMJudgeBundle\Entity\Judging $judging)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJudging', [$judging]);

        return parent::addJudging($judging);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJudging(\DOMJudgeBundle\Entity\Judging $judging)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJudging', [$judging]);

        return parent::removeJudging($judging);
    }

    /**
     * {@inheritDoc}
     */
    public function getJudgings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJudgings', []);

        return parent::getJudgings();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage(\DOMJudgeBundle\Entity\Language $language = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function addFile(\DOMJudgeBundle\Entity\SubmissionFile $file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFile', [$file]);

        return parent::addFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFile(\DOMJudgeBundle\Entity\SubmissionFile $file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFile', [$file]);

        return parent::removeFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', []);

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function addBalloon(\DOMJudgeBundle\Entity\Balloon $balloon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBalloon', [$balloon]);

        return parent::addBalloon($balloon);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBalloon(\DOMJudgeBundle\Entity\Balloon $balloon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBalloon', [$balloon]);

        return parent::removeBalloon($balloon);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalloons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalloons', []);

        return parent::getBalloons();
    }

    /**
     * {@inheritDoc}
     */
    public function setContest(\DOMJudgeBundle\Entity\Contest $contest = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContest', [$contest]);

        return parent::setContest($contest);
    }

    /**
     * {@inheritDoc}
     */
    public function getContest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContest', []);

        return parent::getContest();
    }

    /**
     * {@inheritDoc}
     */
    public function setProblem(\DOMJudgeBundle\Entity\Problem $problem = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProblem', [$problem]);

        return parent::setProblem($problem);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblem', []);

        return parent::getProblem();
    }

}
