<?php

namespace Proxies\__CG__\DOMJudgeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Language extends \DOMJudgeBundle\Entity\Language implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'langid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'name', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'extensions', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'allow_submit', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'allow_judge', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'time_factor', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'compile_script', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'compile_executable', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'submissions'];
        }

        return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'langid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'name', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'extensions', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'allow_submit', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'allow_judge', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'time_factor', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'compile_script', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'compile_executable', '' . "\0" . 'DOMJudgeBundle\\Entity\\Language' . "\0" . 'submissions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Language $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLangid($langid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLangid', [$langid]);

        return parent::setLangid($langid);
    }

    /**
     * {@inheritDoc}
     */
    public function getLangid()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getLangid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLangid', []);

        return parent::getLangid();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtensions($extensions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtensions', [$extensions]);

        return parent::setExtensions($extensions);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtensions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtensions', []);

        return parent::getExtensions();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowSubmit($allowSubmit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowSubmit', [$allowSubmit]);

        return parent::setAllowSubmit($allowSubmit);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowSubmit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowSubmit', []);

        return parent::getAllowSubmit();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowJudge($allowJudge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowJudge', [$allowJudge]);

        return parent::setAllowJudge($allowJudge);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowJudge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowJudge', []);

        return parent::getAllowJudge();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeFactor($timeFactor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeFactor', [$timeFactor]);

        return parent::setTimeFactor($timeFactor);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeFactor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeFactor', []);

        return parent::getTimeFactor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompileScript($compileScript)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompileScript', [$compileScript]);

        return parent::setCompileScript($compileScript);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompileScript()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompileScript', []);

        return parent::getCompileScript();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompileExecutable(\DOMJudgeBundle\Entity\Executable $compileExecutable = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompileExecutable', [$compileExecutable]);

        return parent::setCompileExecutable($compileExecutable);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompileExecutable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompileExecutable', []);

        return parent::getCompileExecutable();
    }

    /**
     * {@inheritDoc}
     */
    public function addSubmission(\DOMJudgeBundle\Entity\Submission $submission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSubmission', [$submission]);

        return parent::addSubmission($submission);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSubmission(\DOMJudgeBundle\Entity\Submission $submission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSubmission', [$submission]);

        return parent::removeSubmission($submission);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmissions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmissions', []);

        return parent::getSubmissions();
    }

}
