<?php

namespace Proxies\__CG__\DOMJudgeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Problem extends \DOMJudgeBundle\Entity\Problem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'probid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'name', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'timelimit', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'memlimit', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'outputlimit', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'special_run', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'special_compare', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'special_compare_args', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'problemtext', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'problemtext_type', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'submissions', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'clarifications', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'contest_problems', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'compare_executable', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'run_executable', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'testcases', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'scorecache'];
        }

        return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'probid', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'name', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'timelimit', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'memlimit', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'outputlimit', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'special_run', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'special_compare', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'special_compare_args', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'problemtext', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'problemtext_type', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'submissions', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'clarifications', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'contest_problems', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'compare_executable', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'run_executable', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'testcases', '' . "\0" . 'DOMJudgeBundle\\Entity\\Problem' . "\0" . 'scorecache'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Problem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProbid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProbid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProbid', []);

        return parent::getProbid();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimelimit($timelimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimelimit', [$timelimit]);

        return parent::setTimelimit($timelimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimelimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimelimit', []);

        return parent::getTimelimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemlimit($memlimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemlimit', [$memlimit]);

        return parent::setMemlimit($memlimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemlimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemlimit', []);

        return parent::getMemlimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setOutputlimit($outputlimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOutputlimit', [$outputlimit]);

        return parent::setOutputlimit($outputlimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getOutputlimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutputlimit', []);

        return parent::getOutputlimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialRun($specialRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialRun', [$specialRun]);

        return parent::setSpecialRun($specialRun);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialRun()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialRun', []);

        return parent::getSpecialRun();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialCompare($specialCompare)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialCompare', [$specialCompare]);

        return parent::setSpecialCompare($specialCompare);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialCompare()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialCompare', []);

        return parent::getSpecialCompare();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialCompareArgs($specialCompareArgs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialCompareArgs', [$specialCompareArgs]);

        return parent::setSpecialCompareArgs($specialCompareArgs);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialCompareArgs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialCompareArgs', []);

        return parent::getSpecialCompareArgs();
    }

    /**
     * {@inheritDoc}
     */
    public function setProblemtext($problemtext)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProblemtext', [$problemtext]);

        return parent::setProblemtext($problemtext);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblemtext()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblemtext', []);

        return parent::getProblemtext();
    }

    /**
     * {@inheritDoc}
     */
    public function setProblemtextType($problemtextType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProblemtextType', [$problemtextType]);

        return parent::setProblemtextType($problemtextType);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblemtextType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblemtextType', []);

        return parent::getProblemtextType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompareExecutable(\DOMJudgeBundle\Entity\Executable $compareExecutable = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompareExecutable', [$compareExecutable]);

        return parent::setCompareExecutable($compareExecutable);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompareExecutable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompareExecutable', []);

        return parent::getCompareExecutable();
    }

    /**
     * {@inheritDoc}
     */
    public function setRunExecutable(\DOMJudgeBundle\Entity\Executable $runExecutable = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRunExecutable', [$runExecutable]);

        return parent::setRunExecutable($runExecutable);
    }

    /**
     * {@inheritDoc}
     */
    public function getRunExecutable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRunExecutable', []);

        return parent::getRunExecutable();
    }

    /**
     * {@inheritDoc}
     */
    public function addTestcase(\DOMJudgeBundle\Entity\Testcase $testcase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTestcase', [$testcase]);

        return parent::addTestcase($testcase);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTestcase(\DOMJudgeBundle\Entity\Testcase $testcase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTestcase', [$testcase]);

        return parent::removeTestcase($testcase);
    }

    /**
     * {@inheritDoc}
     */
    public function getTestcases()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTestcases', []);

        return parent::getTestcases();
    }

    /**
     * {@inheritDoc}
     */
    public function addContestProblem(\DOMJudgeBundle\Entity\ContestProblem $contestProblem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContestProblem', [$contestProblem]);

        return parent::addContestProblem($contestProblem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContestProblem(\DOMJudgeBundle\Entity\ContestProblem $contestProblem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContestProblem', [$contestProblem]);

        return parent::removeContestProblem($contestProblem);
    }

    /**
     * {@inheritDoc}
     */
    public function getContestProblems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContestProblems', []);

        return parent::getContestProblems();
    }

    /**
     * {@inheritDoc}
     */
    public function addSubmission(\DOMJudgeBundle\Entity\Submission $submission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSubmission', [$submission]);

        return parent::addSubmission($submission);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSubmission(\DOMJudgeBundle\Entity\Submission $submission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSubmission', [$submission]);

        return parent::removeSubmission($submission);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmissions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmissions', []);

        return parent::getSubmissions();
    }

    /**
     * {@inheritDoc}
     */
    public function addClarification(\DOMJudgeBundle\Entity\Clarification $clarification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClarification', [$clarification]);

        return parent::addClarification($clarification);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClarification(\DOMJudgeBundle\Entity\Clarification $clarification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClarification', [$clarification]);

        return parent::removeClarification($clarification);
    }

    /**
     * {@inheritDoc}
     */
    public function getClarifications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClarifications', []);

        return parent::getClarifications();
    }

    /**
     * {@inheritDoc}
     */
    public function addScorecache(\DOMJudgeBundle\Entity\ScoreCache $scorecache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addScorecache', [$scorecache]);

        return parent::addScorecache($scorecache);
    }

    /**
     * {@inheritDoc}
     */
    public function removeScorecache(\DOMJudgeBundle\Entity\ScoreCache $scorecache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeScorecache', [$scorecache]);

        return parent::removeScorecache($scorecache);
    }

    /**
     * {@inheritDoc}
     */
    public function getScorecache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScorecache', []);

        return parent::getScorecache();
    }

}
