<?php

namespace Proxies\__CG__\DOMJudgeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RankCache extends \DOMJudgeBundle\Entity\RankCache implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'cid', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'teamid', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'points_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'totaltime_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'points_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'totaltime_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'contest', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'team'];
        }

        return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'cid', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'teamid', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'points_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'totaltime_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'points_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'totaltime_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'contest', '' . "\0" . 'DOMJudgeBundle\\Entity\\RankCache' . "\0" . 'team'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RankCache $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCid($cid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCid', [$cid]);

        return parent::setCid($cid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCid', []);

        return parent::getCid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeamid($teamid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeamid', [$teamid]);

        return parent::setTeamid($teamid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeamid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getTeamid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeamid', []);

        return parent::getTeamid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsRestricted($pointsRestricted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsRestricted', [$pointsRestricted]);

        return parent::setPointsRestricted($pointsRestricted);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsRestricted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsRestricted', []);

        return parent::getPointsRestricted();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotaltimeRestricted($totaltimeRestricted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotaltimeRestricted', [$totaltimeRestricted]);

        return parent::setTotaltimeRestricted($totaltimeRestricted);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotaltimeRestricted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotaltimeRestricted', []);

        return parent::getTotaltimeRestricted();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsPublic($pointsPublic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsPublic', [$pointsPublic]);

        return parent::setPointsPublic($pointsPublic);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsPublic', []);

        return parent::getPointsPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotaltimePublic($totaltimePublic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotaltimePublic', [$totaltimePublic]);

        return parent::setTotaltimePublic($totaltimePublic);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotaltimePublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotaltimePublic', []);

        return parent::getTotaltimePublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setContest(\DOMJudgeBundle\Entity\Contest $contest = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContest', [$contest]);

        return parent::setContest($contest);
    }

    /**
     * {@inheritDoc}
     */
    public function getContest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContest', []);

        return parent::getContest();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeam(\DOMJudgeBundle\Entity\Team $team = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeam', [$team]);

        return parent::setTeam($team);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeam', []);

        return parent::getTeam();
    }

}
