<?php

namespace Proxies\__CG__\DOMJudgeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ScoreCache extends \DOMJudgeBundle\Entity\ScoreCache implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'cid', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'teamid', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'probid', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'submissions_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'pending_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'is_correct_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'solvetime_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'submissions_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'pending_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'is_correct_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'solvetime_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'contest', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'team', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'problem'];
        }

        return ['__isInitialized__', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'cid', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'teamid', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'probid', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'submissions_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'pending_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'is_correct_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'solvetime_restricted', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'submissions_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'pending_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'is_correct_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'solvetime_public', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'contest', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'team', '' . "\0" . 'DOMJudgeBundle\\Entity\\ScoreCache' . "\0" . 'problem'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ScoreCache $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCid($cid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCid', [$cid]);

        return parent::setCid($cid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCid', []);

        return parent::getCid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeamid($teamid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeamid', [$teamid]);

        return parent::setTeamid($teamid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeamid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getTeamid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeamid', []);

        return parent::getTeamid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProbid($probid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProbid', [$probid]);

        return parent::setProbid($probid);
    }

    /**
     * {@inheritDoc}
     */
    public function getProbid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProbid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProbid', []);

        return parent::getProbid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmissionsRestricted($submissionsRestricted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmissionsRestricted', [$submissionsRestricted]);

        return parent::setSubmissionsRestricted($submissionsRestricted);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmissionsRestricted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmissionsRestricted', []);

        return parent::getSubmissionsRestricted();
    }

    /**
     * {@inheritDoc}
     */
    public function setPendingRestricted($pendingRestricted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPendingRestricted', [$pendingRestricted]);

        return parent::setPendingRestricted($pendingRestricted);
    }

    /**
     * {@inheritDoc}
     */
    public function getPendingRestricted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendingRestricted', []);

        return parent::getPendingRestricted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCorrectRestricted($isCorrectRestricted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCorrectRestricted', [$isCorrectRestricted]);

        return parent::setIsCorrectRestricted($isCorrectRestricted);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCorrectRestricted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCorrectRestricted', []);

        return parent::getIsCorrectRestricted();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolvetimeRestricted($solvetimeRestricted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolvetimeRestricted', [$solvetimeRestricted]);

        return parent::setSolvetimeRestricted($solvetimeRestricted);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolvetimeRestricted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolvetimeRestricted', []);

        return parent::getSolvetimeRestricted();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmissionsPublic($submissionsPublic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmissionsPublic', [$submissionsPublic]);

        return parent::setSubmissionsPublic($submissionsPublic);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmissionsPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmissionsPublic', []);

        return parent::getSubmissionsPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setPendingPublic($pendingPublic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPendingPublic', [$pendingPublic]);

        return parent::setPendingPublic($pendingPublic);
    }

    /**
     * {@inheritDoc}
     */
    public function getPendingPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendingPublic', []);

        return parent::getPendingPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCorrectPublic($isCorrectPublic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCorrectPublic', [$isCorrectPublic]);

        return parent::setIsCorrectPublic($isCorrectPublic);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCorrectPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCorrectPublic', []);

        return parent::getIsCorrectPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolvetimePublic($solvetimePublic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolvetimePublic', [$solvetimePublic]);

        return parent::setSolvetimePublic($solvetimePublic);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolvetimePublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolvetimePublic', []);

        return parent::getSolvetimePublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setContest(\DOMJudgeBundle\Entity\Contest $contest = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContest', [$contest]);

        return parent::setContest($contest);
    }

    /**
     * {@inheritDoc}
     */
    public function getContest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContest', []);

        return parent::getContest();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeam(\DOMJudgeBundle\Entity\Team $team = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeam', [$team]);

        return parent::setTeam($team);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeam', []);

        return parent::getTeam();
    }

    /**
     * {@inheritDoc}
     */
    public function setProblem(\DOMJudgeBundle\Entity\Problem $problem = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProblem', [$problem]);

        return parent::setProblem($problem);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblem', []);

        return parent::getProblem();
    }

}
